title: Nuowen Kan
url: "https://main.nuowen.pro"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: Nuowen Kan, 阚诺文
keywords: 阚诺文

footer: yes
footer_url: "https://main.nuowen.pro"
# footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
#  - name: "Resume"
#    link: "resume.pdf"
 - name: "Contact"
   link: "contact"

theme: jekyll-theme-cayman
